version: '3.7'
services:
 influxdb:
  image: influxdb:latest
  container_name: influxdb
  ports:
    - "8086:8086"
  env_file:
    - 'env.influxdb'
  restart: always
  environment:
    - INFLUXDB_DB=d0
    - INFLUXDB_ADMIN_USER=admin
    - INFLUXDB_ADMIN_PASSWORD=admin
  volumes:
    # Data persistency
    # sudo mkdir -p /srv/docker/influxdb/data
    - ./influxdb/data:/var/lib/influxdb

 telegraf:
  image: telegraf:latest
  container_name: telegraf
  links:
    - influxdb
  restart: always
  volumes:
    - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro

 grafana:
   image: grafana/grafana:latest
   environment:
    - GF_INSTALL_PLUGINS=alexanderzobnin-zabbix-app,raintank-worldping-app,vonage-status-panel,grafana-clock-panel,grafana-strava-datasource
    - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=alexanderzobnin-zabbix-app,raintank-worldping-app,vonage-status-panel,grafana-clock-panel,grafana-strava-datasource
    - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=alexanderzobnin-zabbix-datasource,raintank-worldping-app,vonage-status-panel,grafana-clock-panel,grafana-strava-datasource
   ports:
    - 3000:3000
   restart: always
   volumes:
#    - /opt/zabbix/grafana/provisioning/:/etc/grafana/provisioning/
    - ./vol/grafana:/var/lib/grafana