version: '3.7'
services:
 influxdb:
  image: influxdb:latest
  container_name: influxdb
  ports:
    - "8086:8086"
  env_file:
    - 'env.influxdb'
  restart: always
  environment:
    - INFLUXDB_DB=d0
    - INFLUXDB_ADMIN_USER=admin
    - INFLUXDB_ADMIN_PASSWORD=admin
  volumes:
    - ./influxdb/data:/var/lib/influxdb

 telegraf:
  image: telegraf:latest
  container_name: telegraf
  links:
    - influxdb
  restart: always
  volumes:
    - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro

 grafana:
   image: grafana/grafana:latest
   ports:
    - 3000:3000
   restart: always
   volumes:
    - ./vol/grafana:/var/lib/grafana
    - ./provisioning/:/etc/grafana/provisioning/

 portainer:
   image: portainer/portainer-ce:linux-arm
   container_name: portainer
   ports:
    - 9000:9000
   restart: always
   volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - portainer_data:/data
volumes:
  portainer_data:
    external: true