---
- hosts: all
  become: true
  tasks:    
  - name: create directory volume for grafana
    file:
      path: /opt/monitoring/grafana/vol/
      state: directory
  - name: create directory volume for influxdb
    file:
      path: /opt/monitoring/grafana/influxdb/data
      state: directory
  - name: copy telegraf.conf file from source to the destinaton
    copy: src=/Users/piotr/projects/praca-inz/monitoring/telegraf.conf dest=/opt/monitoring/grafana/telegraf.conf 
  - name: copy env.influxdb file from source to the destinaton
    copy: src=/Users/piotr/projects/praca-inz/monitoring/env.influxdb dest=/opt/monitoring/grafana/env.influxdb        
  - name: copy grafana provisioning directory
    copy: 
      src=/Users/piotr/projects/praca-inz/monitoring/provisioning/
      dest=/opt/monitoring/grafana/provisioning/
  - name: copy docker-compose.yml file from source to the destinaton
    copy: src=/Users/piotr/projects/praca-inz/monitoring/docker-compose.yml dest=/opt/monitoring/grafana/docker-compose.yml 
  - name: create volume portainer_data
    command: docker volume create --name portainer_data
  - name: Docker-compose up
    shell:
      cmd: "docker-compose up --force-recreate -d"
      chdir: /opt/monitoring/grafana
  - name: Change permissions on grafana volume
    shell:
      cmd: "chown -R 472.472 ./vol"
      chdir: /opt/monitoring/grafana
  - name: Restart Grafana container
    shell:
      cmd: "docker-compose up --force-recreate -d grafana"
      chdir: /opt/monitoring/grafana
